### ISSUE TITLE
Status update?

### ISSUE THREAD

**Issue by gusmclennan** [JohnBuswell/AusAddressR#1]
Hi John,

I was wondering if you were planning on finishing (or publishing) your AusAddressR package...I have my own local instance of G-NAF running on a PostgreSQL database, and would love some pre-built function to call the database to geocode addresses (return lat and lon), including any available fuzzy matching logic.  Was hoping to find a package, and stumbled across this Github project.  Are you planning on finishing or publishing??  Please let me know if so!   Cheers, Gus

**Comment by matthewsheeran** [comment]
I think his silence is golden..  I am a bit of a GNAF guru as I have worked on it for both one of the data retailers/providers and the search infrastructure of several utilities.
Feel free to get I touch with me here or through GitHub as I am sure I could help you with Dev as well as GIS background. It would.be nice to retail a solution  to completelythe quarterly updates.. ;-)
Kindest Regards,
Matthew

**Comment by gusmclennan** [comment]
Hey Matthew,

Thanks for the offer.  I got one of my guys to write an address parser and fuzzy logic program, which I think is currently working for about 90% of addresses.  I installed the 'poster' R package which is a wrapper for libpostal, which promised to provide an ML-driven address parser that worked for 99.x % of addresses....I couldn't get the parser to detect unit numbers for apartments, or decompose street into street name and street type (e.g. "Hepburn" and "Avenue"), so that was a disappointment.  We need to geocode a shed load of addresses for a product we are working on, so we really need an in-house solution rather than paying for this service.  Not sure what area you are working in, would be good to connect at some stage.  You can reach me at gus.mclennan@thebluerock.com.au (I am a Director for a business called BlueRock Intelligence). Let me know if you are interested in discussing further.  Cheers.
